// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MedicationService.proto

package grpc;

public final class MedicationServiceOuterClass {
  private MedicationServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MedicationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MedicationRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code MedicationRequest}
   */
  public  static final class MedicationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MedicationRequest)
      MedicationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MedicationRequest.newBuilder() to construct.
    private MedicationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MedicationRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MedicationRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.MedicationServiceOuterClass.internal_static_MedicationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.MedicationServiceOuterClass.internal_static_MedicationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.MedicationServiceOuterClass.MedicationRequest.class, grpc.MedicationServiceOuterClass.MedicationRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.MedicationServiceOuterClass.MedicationRequest)) {
        return super.equals(obj);
      }
      grpc.MedicationServiceOuterClass.MedicationRequest other = (grpc.MedicationServiceOuterClass.MedicationRequest) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.MedicationServiceOuterClass.MedicationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.MedicationServiceOuterClass.MedicationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.MedicationServiceOuterClass.MedicationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.MedicationServiceOuterClass.MedicationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.MedicationServiceOuterClass.MedicationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.MedicationServiceOuterClass.MedicationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.MedicationServiceOuterClass.MedicationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.MedicationServiceOuterClass.MedicationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.MedicationServiceOuterClass.MedicationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.MedicationServiceOuterClass.MedicationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.MedicationServiceOuterClass.MedicationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.MedicationServiceOuterClass.MedicationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.MedicationServiceOuterClass.MedicationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MedicationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MedicationRequest)
        grpc.MedicationServiceOuterClass.MedicationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.MedicationServiceOuterClass.internal_static_MedicationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.MedicationServiceOuterClass.internal_static_MedicationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.MedicationServiceOuterClass.MedicationRequest.class, grpc.MedicationServiceOuterClass.MedicationRequest.Builder.class);
      }

      // Construct using grpc.MedicationServiceOuterClass.MedicationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.MedicationServiceOuterClass.internal_static_MedicationRequest_descriptor;
      }

      @java.lang.Override
      public grpc.MedicationServiceOuterClass.MedicationRequest getDefaultInstanceForType() {
        return grpc.MedicationServiceOuterClass.MedicationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.MedicationServiceOuterClass.MedicationRequest build() {
        grpc.MedicationServiceOuterClass.MedicationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.MedicationServiceOuterClass.MedicationRequest buildPartial() {
        grpc.MedicationServiceOuterClass.MedicationRequest result = new grpc.MedicationServiceOuterClass.MedicationRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.MedicationServiceOuterClass.MedicationRequest) {
          return mergeFrom((grpc.MedicationServiceOuterClass.MedicationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.MedicationServiceOuterClass.MedicationRequest other) {
        if (other == grpc.MedicationServiceOuterClass.MedicationRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.MedicationServiceOuterClass.MedicationRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.MedicationServiceOuterClass.MedicationRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MedicationRequest)
    }

    // @@protoc_insertion_point(class_scope:MedicationRequest)
    private static final grpc.MedicationServiceOuterClass.MedicationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.MedicationServiceOuterClass.MedicationRequest();
    }

    public static grpc.MedicationServiceOuterClass.MedicationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MedicationRequest>
        PARSER = new com.google.protobuf.AbstractParser<MedicationRequest>() {
      @java.lang.Override
      public MedicationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MedicationRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MedicationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MedicationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.MedicationServiceOuterClass.MedicationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MedicationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Medication)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string medicationName = 1;</code>
     */
    java.lang.String getMedicationName();
    /**
     * <code>string medicationName = 1;</code>
     */
    com.google.protobuf.ByteString
        getMedicationNameBytes();

    /**
     * <code>string dailyInterval = 2;</code>
     */
    java.lang.String getDailyInterval();
    /**
     * <code>string dailyInterval = 2;</code>
     */
    com.google.protobuf.ByteString
        getDailyIntervalBytes();
  }
  /**
   * Protobuf type {@code Medication}
   */
  public  static final class Medication extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Medication)
      MedicationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Medication.newBuilder() to construct.
    private Medication(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Medication() {
      medicationName_ = "";
      dailyInterval_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Medication(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              medicationName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              dailyInterval_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.MedicationServiceOuterClass.internal_static_Medication_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.MedicationServiceOuterClass.internal_static_Medication_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.MedicationServiceOuterClass.Medication.class, grpc.MedicationServiceOuterClass.Medication.Builder.class);
    }

    public static final int MEDICATIONNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object medicationName_;
    /**
     * <code>string medicationName = 1;</code>
     */
    public java.lang.String getMedicationName() {
      java.lang.Object ref = medicationName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        medicationName_ = s;
        return s;
      }
    }
    /**
     * <code>string medicationName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMedicationNameBytes() {
      java.lang.Object ref = medicationName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        medicationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DAILYINTERVAL_FIELD_NUMBER = 2;
    private volatile java.lang.Object dailyInterval_;
    /**
     * <code>string dailyInterval = 2;</code>
     */
    public java.lang.String getDailyInterval() {
      java.lang.Object ref = dailyInterval_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dailyInterval_ = s;
        return s;
      }
    }
    /**
     * <code>string dailyInterval = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDailyIntervalBytes() {
      java.lang.Object ref = dailyInterval_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dailyInterval_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMedicationNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, medicationName_);
      }
      if (!getDailyIntervalBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dailyInterval_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMedicationNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, medicationName_);
      }
      if (!getDailyIntervalBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dailyInterval_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.MedicationServiceOuterClass.Medication)) {
        return super.equals(obj);
      }
      grpc.MedicationServiceOuterClass.Medication other = (grpc.MedicationServiceOuterClass.Medication) obj;

      boolean result = true;
      result = result && getMedicationName()
          .equals(other.getMedicationName());
      result = result && getDailyInterval()
          .equals(other.getDailyInterval());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEDICATIONNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMedicationName().hashCode();
      hash = (37 * hash) + DAILYINTERVAL_FIELD_NUMBER;
      hash = (53 * hash) + getDailyInterval().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.MedicationServiceOuterClass.Medication parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.MedicationServiceOuterClass.Medication parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.MedicationServiceOuterClass.Medication parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.MedicationServiceOuterClass.Medication parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.MedicationServiceOuterClass.Medication parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.MedicationServiceOuterClass.Medication parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.MedicationServiceOuterClass.Medication parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.MedicationServiceOuterClass.Medication parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.MedicationServiceOuterClass.Medication parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.MedicationServiceOuterClass.Medication parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.MedicationServiceOuterClass.Medication parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.MedicationServiceOuterClass.Medication parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.MedicationServiceOuterClass.Medication prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Medication}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Medication)
        grpc.MedicationServiceOuterClass.MedicationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.MedicationServiceOuterClass.internal_static_Medication_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.MedicationServiceOuterClass.internal_static_Medication_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.MedicationServiceOuterClass.Medication.class, grpc.MedicationServiceOuterClass.Medication.Builder.class);
      }

      // Construct using grpc.MedicationServiceOuterClass.Medication.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        medicationName_ = "";

        dailyInterval_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.MedicationServiceOuterClass.internal_static_Medication_descriptor;
      }

      @java.lang.Override
      public grpc.MedicationServiceOuterClass.Medication getDefaultInstanceForType() {
        return grpc.MedicationServiceOuterClass.Medication.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.MedicationServiceOuterClass.Medication build() {
        grpc.MedicationServiceOuterClass.Medication result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.MedicationServiceOuterClass.Medication buildPartial() {
        grpc.MedicationServiceOuterClass.Medication result = new grpc.MedicationServiceOuterClass.Medication(this);
        result.medicationName_ = medicationName_;
        result.dailyInterval_ = dailyInterval_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.MedicationServiceOuterClass.Medication) {
          return mergeFrom((grpc.MedicationServiceOuterClass.Medication)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.MedicationServiceOuterClass.Medication other) {
        if (other == grpc.MedicationServiceOuterClass.Medication.getDefaultInstance()) return this;
        if (!other.getMedicationName().isEmpty()) {
          medicationName_ = other.medicationName_;
          onChanged();
        }
        if (!other.getDailyInterval().isEmpty()) {
          dailyInterval_ = other.dailyInterval_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.MedicationServiceOuterClass.Medication parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.MedicationServiceOuterClass.Medication) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object medicationName_ = "";
      /**
       * <code>string medicationName = 1;</code>
       */
      public java.lang.String getMedicationName() {
        java.lang.Object ref = medicationName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          medicationName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string medicationName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMedicationNameBytes() {
        java.lang.Object ref = medicationName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          medicationName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string medicationName = 1;</code>
       */
      public Builder setMedicationName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        medicationName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string medicationName = 1;</code>
       */
      public Builder clearMedicationName() {
        
        medicationName_ = getDefaultInstance().getMedicationName();
        onChanged();
        return this;
      }
      /**
       * <code>string medicationName = 1;</code>
       */
      public Builder setMedicationNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        medicationName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dailyInterval_ = "";
      /**
       * <code>string dailyInterval = 2;</code>
       */
      public java.lang.String getDailyInterval() {
        java.lang.Object ref = dailyInterval_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dailyInterval_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dailyInterval = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDailyIntervalBytes() {
        java.lang.Object ref = dailyInterval_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dailyInterval_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dailyInterval = 2;</code>
       */
      public Builder setDailyInterval(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dailyInterval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dailyInterval = 2;</code>
       */
      public Builder clearDailyInterval() {
        
        dailyInterval_ = getDefaultInstance().getDailyInterval();
        onChanged();
        return this;
      }
      /**
       * <code>string dailyInterval = 2;</code>
       */
      public Builder setDailyIntervalBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dailyInterval_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Medication)
    }

    // @@protoc_insertion_point(class_scope:Medication)
    private static final grpc.MedicationServiceOuterClass.Medication DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.MedicationServiceOuterClass.Medication();
    }

    public static grpc.MedicationServiceOuterClass.Medication getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Medication>
        PARSER = new com.google.protobuf.AbstractParser<Medication>() {
      @java.lang.Override
      public Medication parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Medication(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Medication> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Medication> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.MedicationServiceOuterClass.Medication getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MedicationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MedicationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Medication medications = 1;</code>
     */
    java.util.List<grpc.MedicationServiceOuterClass.Medication> 
        getMedicationsList();
    /**
     * <code>repeated .Medication medications = 1;</code>
     */
    grpc.MedicationServiceOuterClass.Medication getMedications(int index);
    /**
     * <code>repeated .Medication medications = 1;</code>
     */
    int getMedicationsCount();
    /**
     * <code>repeated .Medication medications = 1;</code>
     */
    java.util.List<? extends grpc.MedicationServiceOuterClass.MedicationOrBuilder> 
        getMedicationsOrBuilderList();
    /**
     * <code>repeated .Medication medications = 1;</code>
     */
    grpc.MedicationServiceOuterClass.MedicationOrBuilder getMedicationsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code MedicationResponse}
   */
  public  static final class MedicationResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MedicationResponse)
      MedicationResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MedicationResponse.newBuilder() to construct.
    private MedicationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MedicationResponse() {
      medications_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MedicationResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                medications_ = new java.util.ArrayList<grpc.MedicationServiceOuterClass.Medication>();
                mutable_bitField0_ |= 0x00000001;
              }
              medications_.add(
                  input.readMessage(grpc.MedicationServiceOuterClass.Medication.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          medications_ = java.util.Collections.unmodifiableList(medications_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.MedicationServiceOuterClass.internal_static_MedicationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.MedicationServiceOuterClass.internal_static_MedicationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.MedicationServiceOuterClass.MedicationResponse.class, grpc.MedicationServiceOuterClass.MedicationResponse.Builder.class);
    }

    public static final int MEDICATIONS_FIELD_NUMBER = 1;
    private java.util.List<grpc.MedicationServiceOuterClass.Medication> medications_;
    /**
     * <code>repeated .Medication medications = 1;</code>
     */
    public java.util.List<grpc.MedicationServiceOuterClass.Medication> getMedicationsList() {
      return medications_;
    }
    /**
     * <code>repeated .Medication medications = 1;</code>
     */
    public java.util.List<? extends grpc.MedicationServiceOuterClass.MedicationOrBuilder> 
        getMedicationsOrBuilderList() {
      return medications_;
    }
    /**
     * <code>repeated .Medication medications = 1;</code>
     */
    public int getMedicationsCount() {
      return medications_.size();
    }
    /**
     * <code>repeated .Medication medications = 1;</code>
     */
    public grpc.MedicationServiceOuterClass.Medication getMedications(int index) {
      return medications_.get(index);
    }
    /**
     * <code>repeated .Medication medications = 1;</code>
     */
    public grpc.MedicationServiceOuterClass.MedicationOrBuilder getMedicationsOrBuilder(
        int index) {
      return medications_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < medications_.size(); i++) {
        output.writeMessage(1, medications_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < medications_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, medications_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.MedicationServiceOuterClass.MedicationResponse)) {
        return super.equals(obj);
      }
      grpc.MedicationServiceOuterClass.MedicationResponse other = (grpc.MedicationServiceOuterClass.MedicationResponse) obj;

      boolean result = true;
      result = result && getMedicationsList()
          .equals(other.getMedicationsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMedicationsCount() > 0) {
        hash = (37 * hash) + MEDICATIONS_FIELD_NUMBER;
        hash = (53 * hash) + getMedicationsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.MedicationServiceOuterClass.MedicationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.MedicationServiceOuterClass.MedicationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.MedicationServiceOuterClass.MedicationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.MedicationServiceOuterClass.MedicationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.MedicationServiceOuterClass.MedicationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.MedicationServiceOuterClass.MedicationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.MedicationServiceOuterClass.MedicationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.MedicationServiceOuterClass.MedicationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.MedicationServiceOuterClass.MedicationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.MedicationServiceOuterClass.MedicationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.MedicationServiceOuterClass.MedicationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.MedicationServiceOuterClass.MedicationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.MedicationServiceOuterClass.MedicationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MedicationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MedicationResponse)
        grpc.MedicationServiceOuterClass.MedicationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.MedicationServiceOuterClass.internal_static_MedicationResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.MedicationServiceOuterClass.internal_static_MedicationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.MedicationServiceOuterClass.MedicationResponse.class, grpc.MedicationServiceOuterClass.MedicationResponse.Builder.class);
      }

      // Construct using grpc.MedicationServiceOuterClass.MedicationResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMedicationsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (medicationsBuilder_ == null) {
          medications_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          medicationsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.MedicationServiceOuterClass.internal_static_MedicationResponse_descriptor;
      }

      @java.lang.Override
      public grpc.MedicationServiceOuterClass.MedicationResponse getDefaultInstanceForType() {
        return grpc.MedicationServiceOuterClass.MedicationResponse.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.MedicationServiceOuterClass.MedicationResponse build() {
        grpc.MedicationServiceOuterClass.MedicationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.MedicationServiceOuterClass.MedicationResponse buildPartial() {
        grpc.MedicationServiceOuterClass.MedicationResponse result = new grpc.MedicationServiceOuterClass.MedicationResponse(this);
        int from_bitField0_ = bitField0_;
        if (medicationsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            medications_ = java.util.Collections.unmodifiableList(medications_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.medications_ = medications_;
        } else {
          result.medications_ = medicationsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.MedicationServiceOuterClass.MedicationResponse) {
          return mergeFrom((grpc.MedicationServiceOuterClass.MedicationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.MedicationServiceOuterClass.MedicationResponse other) {
        if (other == grpc.MedicationServiceOuterClass.MedicationResponse.getDefaultInstance()) return this;
        if (medicationsBuilder_ == null) {
          if (!other.medications_.isEmpty()) {
            if (medications_.isEmpty()) {
              medications_ = other.medications_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMedicationsIsMutable();
              medications_.addAll(other.medications_);
            }
            onChanged();
          }
        } else {
          if (!other.medications_.isEmpty()) {
            if (medicationsBuilder_.isEmpty()) {
              medicationsBuilder_.dispose();
              medicationsBuilder_ = null;
              medications_ = other.medications_;
              bitField0_ = (bitField0_ & ~0x00000001);
              medicationsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMedicationsFieldBuilder() : null;
            } else {
              medicationsBuilder_.addAllMessages(other.medications_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.MedicationServiceOuterClass.MedicationResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.MedicationServiceOuterClass.MedicationResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<grpc.MedicationServiceOuterClass.Medication> medications_ =
        java.util.Collections.emptyList();
      private void ensureMedicationsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          medications_ = new java.util.ArrayList<grpc.MedicationServiceOuterClass.Medication>(medications_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          grpc.MedicationServiceOuterClass.Medication, grpc.MedicationServiceOuterClass.Medication.Builder, grpc.MedicationServiceOuterClass.MedicationOrBuilder> medicationsBuilder_;

      /**
       * <code>repeated .Medication medications = 1;</code>
       */
      public java.util.List<grpc.MedicationServiceOuterClass.Medication> getMedicationsList() {
        if (medicationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(medications_);
        } else {
          return medicationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Medication medications = 1;</code>
       */
      public int getMedicationsCount() {
        if (medicationsBuilder_ == null) {
          return medications_.size();
        } else {
          return medicationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Medication medications = 1;</code>
       */
      public grpc.MedicationServiceOuterClass.Medication getMedications(int index) {
        if (medicationsBuilder_ == null) {
          return medications_.get(index);
        } else {
          return medicationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Medication medications = 1;</code>
       */
      public Builder setMedications(
          int index, grpc.MedicationServiceOuterClass.Medication value) {
        if (medicationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMedicationsIsMutable();
          medications_.set(index, value);
          onChanged();
        } else {
          medicationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Medication medications = 1;</code>
       */
      public Builder setMedications(
          int index, grpc.MedicationServiceOuterClass.Medication.Builder builderForValue) {
        if (medicationsBuilder_ == null) {
          ensureMedicationsIsMutable();
          medications_.set(index, builderForValue.build());
          onChanged();
        } else {
          medicationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Medication medications = 1;</code>
       */
      public Builder addMedications(grpc.MedicationServiceOuterClass.Medication value) {
        if (medicationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMedicationsIsMutable();
          medications_.add(value);
          onChanged();
        } else {
          medicationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Medication medications = 1;</code>
       */
      public Builder addMedications(
          int index, grpc.MedicationServiceOuterClass.Medication value) {
        if (medicationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMedicationsIsMutable();
          medications_.add(index, value);
          onChanged();
        } else {
          medicationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Medication medications = 1;</code>
       */
      public Builder addMedications(
          grpc.MedicationServiceOuterClass.Medication.Builder builderForValue) {
        if (medicationsBuilder_ == null) {
          ensureMedicationsIsMutable();
          medications_.add(builderForValue.build());
          onChanged();
        } else {
          medicationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Medication medications = 1;</code>
       */
      public Builder addMedications(
          int index, grpc.MedicationServiceOuterClass.Medication.Builder builderForValue) {
        if (medicationsBuilder_ == null) {
          ensureMedicationsIsMutable();
          medications_.add(index, builderForValue.build());
          onChanged();
        } else {
          medicationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Medication medications = 1;</code>
       */
      public Builder addAllMedications(
          java.lang.Iterable<? extends grpc.MedicationServiceOuterClass.Medication> values) {
        if (medicationsBuilder_ == null) {
          ensureMedicationsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, medications_);
          onChanged();
        } else {
          medicationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Medication medications = 1;</code>
       */
      public Builder clearMedications() {
        if (medicationsBuilder_ == null) {
          medications_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          medicationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Medication medications = 1;</code>
       */
      public Builder removeMedications(int index) {
        if (medicationsBuilder_ == null) {
          ensureMedicationsIsMutable();
          medications_.remove(index);
          onChanged();
        } else {
          medicationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Medication medications = 1;</code>
       */
      public grpc.MedicationServiceOuterClass.Medication.Builder getMedicationsBuilder(
          int index) {
        return getMedicationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Medication medications = 1;</code>
       */
      public grpc.MedicationServiceOuterClass.MedicationOrBuilder getMedicationsOrBuilder(
          int index) {
        if (medicationsBuilder_ == null) {
          return medications_.get(index);  } else {
          return medicationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Medication medications = 1;</code>
       */
      public java.util.List<? extends grpc.MedicationServiceOuterClass.MedicationOrBuilder> 
           getMedicationsOrBuilderList() {
        if (medicationsBuilder_ != null) {
          return medicationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(medications_);
        }
      }
      /**
       * <code>repeated .Medication medications = 1;</code>
       */
      public grpc.MedicationServiceOuterClass.Medication.Builder addMedicationsBuilder() {
        return getMedicationsFieldBuilder().addBuilder(
            grpc.MedicationServiceOuterClass.Medication.getDefaultInstance());
      }
      /**
       * <code>repeated .Medication medications = 1;</code>
       */
      public grpc.MedicationServiceOuterClass.Medication.Builder addMedicationsBuilder(
          int index) {
        return getMedicationsFieldBuilder().addBuilder(
            index, grpc.MedicationServiceOuterClass.Medication.getDefaultInstance());
      }
      /**
       * <code>repeated .Medication medications = 1;</code>
       */
      public java.util.List<grpc.MedicationServiceOuterClass.Medication.Builder> 
           getMedicationsBuilderList() {
        return getMedicationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          grpc.MedicationServiceOuterClass.Medication, grpc.MedicationServiceOuterClass.Medication.Builder, grpc.MedicationServiceOuterClass.MedicationOrBuilder> 
          getMedicationsFieldBuilder() {
        if (medicationsBuilder_ == null) {
          medicationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              grpc.MedicationServiceOuterClass.Medication, grpc.MedicationServiceOuterClass.Medication.Builder, grpc.MedicationServiceOuterClass.MedicationOrBuilder>(
                  medications_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          medications_ = null;
        }
        return medicationsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MedicationResponse)
    }

    // @@protoc_insertion_point(class_scope:MedicationResponse)
    private static final grpc.MedicationServiceOuterClass.MedicationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.MedicationServiceOuterClass.MedicationResponse();
    }

    public static grpc.MedicationServiceOuterClass.MedicationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MedicationResponse>
        PARSER = new com.google.protobuf.AbstractParser<MedicationResponse>() {
      @java.lang.Override
      public MedicationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MedicationResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MedicationResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MedicationResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.MedicationServiceOuterClass.MedicationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MedicationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MedicationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Medication_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Medication_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MedicationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MedicationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027MedicationService.proto\"\023\n\021MedicationR" +
      "equest\";\n\nMedication\022\026\n\016medicationName\030\001" +
      " \001(\t\022\025\n\rdailyInterval\030\002 \001(\t\"6\n\022Medicatio" +
      "nResponse\022 \n\013medications\030\001 \003(\0132\013.Medicat" +
      "ion2M\n\021MedicationService\0228\n\rgetMedicatio" +
      "n\022\022.MedicationRequest\032\023.MedicationRespon" +
      "seB\006\n\004grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MedicationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MedicationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MedicationRequest_descriptor,
        new java.lang.String[] { });
    internal_static_Medication_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Medication_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Medication_descriptor,
        new java.lang.String[] { "MedicationName", "DailyInterval", });
    internal_static_MedicationResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_MedicationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MedicationResponse_descriptor,
        new java.lang.String[] { "Medications", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
